In [1]:
import numpy as np

# Extracting numeric data as NumPy arrays for future analysis
votes = np.array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])
costs = np.array(["'800.0'" ,"'800.0'", "'800.0'", "'300.0'", "'600.0'", "'600.0'", "'600.0'", "'700.0'" ,"'550.0'", "'500.0'"])

print("Votes (Array):", votes)
print("Costs (Array):", costs)

Votes (Array): [ 775  787  918   88  166  286 2556  324  504  402]
Costs (Array): ["'800.0'" "'800.0'" "'800.0'" "'300.0'" "'600.0'" "'600.0'" "'600.0'"
 "'700.0'" "'550.0'" "'500.0'"]


In [5]:
print(votes.shape)
print(votes.ndim)
print(votes.size)

(10,)
1
10


In [7]:
two_d_array = np.array([votes,costs])

In [11]:
print(two_d_array)
print(two_d_array.size)
print(two_d_array.ndim)
print(two_d_array.shape)

[['775' '787' '918' '88' '166' '286' '2556' '324' '504' '402']
 ["'800.0'" "'800.0'" "'800.0'" "'300.0'" "'600.0'" "'600.0'" "'600.0'"
  "'700.0'" "'550.0'" "'500.0'"]]
20
2
(2, 10)


In [12]:
trans_2d_array = two_d_array.T

In [14]:
print(trans_2d_array.shape)

(10, 2)


In [ ]:
print(np.arange(1,9))
print(np.arange(1,9,2))


[1 2 3 4 5 6 7 8]
[1 3 5 7]


In [ ]:
print(np.arange(1,9,0.5))

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5]


In [22]:
costs

array(["'800.0'", "'800.0'", "'800.0'", "'300.0'", "'600.0'", "'600.0'",
       "'600.0'", "'700.0'", "'550.0'", "'500.0'"], dtype='<U7')

In [38]:
new_costs = np.char.replace(costs,",","")
new_costs1 = np.char.replace(costs,"'","")

In [40]:
print(new_costs1)
new_costs.dtype

['800.0' '800.0' '800.0' '300.0' '600.0' '600.0' '600.0' '700.0' '550.0'
 '500.0']


dtype('<U7')

In [42]:
print(new_costs[:5])

["'800.0'" "'800.0'" "'800.0'" "'300.0'" "'600.0'"]


In [47]:
print(votes)
print(votes <325)
print(votes[votes < 325])


[ 775  787  918   88  166  286 2556  324  504  402]
[False False False  True  True  True False  True False False]
[ 88 166 286 324]


In [60]:
print(two_d_array)
print(two_d_array[:,1])

[['775' '787' '918' '88' '166' '286' '2556' '324' '504' '402']
 ["'800.0'" "'800.0'" "'800.0'" "'300.0'" "'600.0'" "'600.0'" "'600.0'"
  "'700.0'" "'550.0'" "'500.0'"]]
['787' "'800.0'"]


In [65]:
# Take a sample of 50 restaurants
sample_votes = np.array([775, 787, 918, 88, 166, 286, 2556, 324, 504, 402, 150, 164, 424, 918, 90, 133, 144, 93, 62, 180, 62, 148, 219, 506, 172, 415, 230, 1647, 4884, 133, 286, 540, 2556, 36, 244, 804, 679, 245, 345, 618, 1047, 627, 354, 244, 163, 808, 1720, 868, 520, 299])
sample_costs = np.array([800.0, 800.0, 800.0, 300.0, 600.0, 600.0, 600.0, 700.0, 550.0, 500.0, 600.0, 500.0, 450.0, 800.0, 650.0, 800.0, 700.0, 300.0, 400.0, 500.0, 600.0, 550.0, 600.0, 500.0, 750.0, 500.0, 650.0, 600.0, 750.0, 200.0, 500.0, 800.0, 600.0, 400.0, 300.0, 450.0, 850.0, 300.0, 400.0, 750.0, 450.0, 450.0, 800.0, 800.0, 800.0, 850.0, 400.0, 1200.0, 300.0, 300.0])

# Create a 2D array: rows = restaurants, columns = [votes, costs]
restaurants_data = np.column_stack((sample_votes, sample_costs))

print("2D Array (votes, costs):\n", restaurants_data[:10,:])
print("Shape:", restaurants_data.shape)
print("Dimensions:", restaurants_data.ndim)  # 2D

2D Array (votes, costs):
 [[ 775.  800.]
 [ 787.  800.]
 [ 918.  800.]
 [  88.  300.]
 [ 166.  600.]
 [ 286.  600.]
 [2556.  600.]
 [ 324.  700.]
 [ 504.  550.]
 [ 402.  500.]]
Shape: (50, 2)
Dimensions: 2


In [69]:
rows =restaurants_data[:10,:]
print(rows)
print(rows.ndim)
print(rows.size)

[[ 775.  800.]
 [ 787.  800.]
 [ 918.  800.]
 [  88.  300.]
 [ 166.  600.]
 [ 286.  600.]
 [2556.  600.]
 [ 324.  700.]
 [ 504.  550.]
 [ 402.  500.]]
2
20


In [84]:
print(rows.reshape(-1,4))

[[ 775.  800.  787.  800.]
 [ 918.  800.   88.  300.]
 [ 166.  600.  286.  600.]
 [2556.  600.  324.  700.]
 [ 504.  550.  402.  500.]]
