In [1]:
import numpy as np

In [10]:
votes = np.array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])
costs = np.array(["'800.0'" ,"'800.0'", "'800.0'", "'300.0'", "'600.0'", "'600.0'", "'600.0'", "'700.0'" ,"'550.0'", "'500.0'"])


In [11]:
print(votes.shape)
print(votes.size)
print(votes.ndim)

(10,)
10
1


In [17]:
print(np.array([votes,costs]).shape)

(2, 10)


In [14]:
two_d_data = np.array([votes,costs]).T

In [16]:
print(two_d_data)
print(two_d_data.size)
print(two_d_data.shape)
print(two_d_data.ndim)

[['775' "'800.0'"]
 ['787' "'800.0'"]
 ['918' "'800.0'"]
 ['88' "'300.0'"]
 ['166' "'600.0'"]
 ['286' "'600.0'"]
 ['2556' "'600.0'"]
 ['324' "'700.0'"]
 ['504' "'550.0'"]
 ['402' "'500.0'"]]
20
(10, 2)
2


In [18]:
number = np.arange(1,5)

In [19]:
print(costs.dtype)

<U7


In [20]:
costs

array(["'800.0'", "'800.0'", "'800.0'", "'300.0'", "'600.0'", "'600.0'",
       "'600.0'", "'700.0'", "'550.0'", "'500.0'"], dtype='<U7')

In [21]:
cleaned_costs = np.char.replace(costs,"'","")

In [22]:
cleaned_costs

array(['800.0', '800.0', '800.0', '300.0', '600.0', '600.0', '600.0',
       '700.0', '550.0', '500.0'], dtype='<U5')

In [23]:
cleaned_costs.dtype

dtype('<U5')

In [24]:
float_costs = cleaned_costs.astype(float)

In [33]:
votes

array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])

In [35]:
votes[1:2]

array([787])

In [31]:
print(votes[-1])

402


In [41]:
t = np.array([2,3,4,5,6,7])

In [43]:
t

array([2, 3, 4, 5, 6, 7])

In [45]:
print(t[1])

3


In [46]:
print(t[[2,3]])

[4 5]


In [1]:
list1= []

list1.append('Venkatesh')

In [2]:
list1

['Venkatesh']

In [3]:
list1.append('crea')

In [4]:
list1

['Venkatesh', 'crea']

In [5]:
[print(x) for x in list1]

Venkatesh
crea


[None, None]

In [8]:
v=[x for x in range(10)]
print(v)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [9]:
lst = ['Asabeneh', 250, True, {'country':'Finland', 'city':'Helsinki'}]

In [10]:
c = [item for item in lst]
print(c)

['Asabeneh', 250, True, {'country': 'Finland', 'city': 'Helsinki'}]


In [11]:
c[0]

'Asabeneh'

In [12]:
c[1]

250

In [26]:
type(c[3])

dict

In [46]:
d={key for key,value in c[3].items()}
d


{'city', 'country'}