In [4]:
import numpy as np

# Example 2D array of size (n, n)
n = 3
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Rotate the matrix 90 degrees clockwise
rotated_matrix = np.rot90(matrix, 2)

print("Original Matrix:")
print(matrix)

print("\nRotated Matrix (90° clockwise):")
print(rotated_matrix)


Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Rotated Matrix (90° clockwise):
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [14]:
import numpy as np
# Declaring a 2D matrix (3x3 matrix)
mat = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
rotate_img(mat)
def rotate_img(mat):
    '''mat -> A 2d numpy array
       output -> A 2d numpy array is expected to be returned'''
    # Transpose the matrix
    transposed_mat = np.array(mat).T
    print(transposed_mat)
    # Reverse each row
    rotated_matrix1 = np.array([row[::-1] for row in transposed_mat])
    rotated_matrix2=transposed_mat[::-1]
    rotated_matrix3 = mat[::-1, ::-1]
    print(rotated_matrix1)
    print(rotated_matrix2)
    print(rotated_matrix3)
    return rotated_matrix3

# Declaring a 2D matrix (3x3 matrix)
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
#rotate_img(matrix)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


TypeError: list indices must be integers or slices, not tuple

In [21]:
import numpy as np
x = np.array([[200,200,200],[300,300,300],[400,400,400]])
v = np.array([200,300,400])
print(v[:,None])
print((x / v[:,None])[1][1]) 


import numpy as np
p = np.array([[0], [10], [20]])
q = np.array([10, 11, 12]) 
print((p + q)[1][1]) 

[[200]
 [300]
 [400]]
1.0
21


In [25]:
np.array([1, 2, 3]).T

array([1, 2, 3])

In [26]:
B = np.array([1, 2, 3])  # Shape (1, 3)

# Transpose B to make it a (3, 1) matrix
B = B[:, None]
B

array([[1],
       [2],
       [3]])

In [27]:
import numpy as np
a = np.array([[16, 5], [81, 6], [33, 1]])
x=np.transpose(a).reshape(2,3)
print(x)
print(x.flatten())

[[16 81 33]
 [ 5  6  1]]
[16 81 33  5  6  1]


In [29]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [59]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[11,22,33],[44,55,66]])

b = np.array(a).T

print(b)

c =np.array([row[::-1] for row in b])

print(c)

[[ 1  4  7 11 44]
 [ 2  5  8 22 55]
 [ 3  6  9 33 66]]
[[44 11  7  4  1]
 [55 22  8  5  2]
 [66 33  9  6  3]]


In [63]:
numeric_data = np.array([
    [4.1, 775.0, 800.0],
    [3.8, 787.0, 800.0],
    [4.0, 918.0, 800.0],
    [2.6, 88.0, 300.0],
    [1.1, 166.0, 600.0],
    [3.5, 286.0, 600.0],
    [4.7, 2556.0, 600.0],
    [2.5, 324.0, 700.0],
    [2.8, 504.0, 550.0],
    [3.4, 402.0, 500.0]
])

ratings = numeric_data[:, 0]  # Extract 'rate' column
votes=numeric_data[:,1]
print(ratings)
print(votes)
print(ratings*votes)

[4.1 3.8 4.  2.6 1.1 3.5 4.7 2.5 2.8 3.4]
[ 775.  787.  918.   88.  166.  286. 2556.  324.  504.  402.]
[ 3177.5  2990.6  3672.    228.8   182.6  1001.  12013.2   810.   1411.2
  1366.8]


In [64]:
numeric_data = np.array([
    [4.1, 775.0, 800.0],
    [3.8, 787.0, 800.0],
    [4.0, 918.0, 800.0],
    [2.6, 88.0, 300.0],
    [1.1, 166.0, 600.0],
    [3.5, 286.0, 600.0],
    [4.7, 2556.0, 600.0],
    [2.5, 324.0, 700.0],
    [2.8, 504.0, 550.0],
    [3.4, 402.0, 500.0]
])

# Create a random transformation matrix
transformation_matrix = np.array([[1.2, 0.8, 0.5],
                                   [0.5, 1.5, 1.0],
                                   [0.7, 0.6, 1.8]])

# Matrix multiplication using np.dot()
transformed_data_dot = np.dot(numeric_data, transformation_matrix)

print(transformed_data_dot)

[[ 952.42 1645.78 2217.05]
 [ 958.06 1663.54 2228.9 ]
 [1023.8  1860.2  2360.  ]
 [ 257.12  314.08  629.3 ]
 [ 504.32  609.88 1246.55]
 [ 567.2   791.8  1367.75]
 [1703.64 4197.76 3638.35]
 [ 655.    908.   1585.25]
 [ 640.36 1088.24 1495.4 ]
 [ 555.08  905.72 1303.7 ]]


In [66]:
import numpy as np
print(np.sort(np.array(['Ram','Astha','Raghavendra'])))

arr1 = np.array(['Ram','Astha','Brahat'])
arr2 = np.array(['Shyam','Kalyan','Naveen'])
print(arr1 > arr2)

['Astha' 'Raghavendra' 'Ram']
[False False False]


In [18]:
import numpy as np
a = np.array([[6, 28], [8, 56], [7, 19]])
x = np.transpose(a)
print(x.tolist())

[[6, 8, 7], [28, 56, 19]]


In [70]:
import numpy as np
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

#print(np.hstack((arr, arr[:, 0])).shape)
print(np.hstack((arr, arr[:, [0]])).shape)
print(np.hstack((arr, arr[:, [0]])).shape)
print(np.hstack((arr,arr[:, 0])) )

(3, 4)
(3, 4)


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [71]:
arr1 = np.array([1,2,3,6,3,2]) 
arr2 = np.array([4,2,1,3,3,2]) 
arr3 = np.zeros(len(arr1)) 
print(arr3)

[0. 0. 0. 0. 0. 0.]


In [1]:
import numpy as np
print(np.sort(np.array(['Ram','Astha','Raghavendra'])))

['Astha' 'Raghavendra' 'Ram']


In [2]:

#a. What is the last element of the output?

import numpy as np
print(np.sort(np.array(['Ram','Astha','Raghavendra'])))


['Astha' 'Raghavendra' 'Ram']


In [3]:
#b. What is the output of the code snippet given below?

arr1 = np.array(['Ram','Astha','Brahat'])
arr2 = np.array(['Shyam','Kalyan','Naveen'])
arr1 > arr2

array([False, False, False])

In [ ]:
import numpy as np
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

#an1 = np.hstack((arr, arr[:, 0])).shape #= (3, 4) --error


an2 = np.hstack((arr, arr[:, [0]])).shape #= (3, 4)


an3 = np.hstack((arr, arr[:, [0]])).shape #(4, 3)


#an4 = np.hstack((arr,arr[:, 0])) #=> Throws Error

#print(an1)

print(an2)

print(an3)

#print(an4)

(3, 4)
(3, 4)


In [14]:
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(arr[:,0])
print(arr[:,[0]])

[1 4 7]
[[1]
 [4]
 [7]]


In [15]:
import numpy as np
arr= np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]])
arr1 = np.array([[2,2,2,2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr,arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [16]:
import numpy as np
arr= np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]])
arr1 = np.array([[2],[2],[2],[2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [17]:
import numpy as np
arr= np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]])
arr1 = 2
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [22]:
import numpy as np
bird = ['sparrow', 'peacock', 'parrot', 'owl', 'peacock', 'macaw', 'macaw', 'parrot', 'macaw', 'peacock']  
age = [6, 1, 6, 5, 7, 6, 0, 9, 0, 7]
# Find the index of the maximum age
max_age_index = np.argmax(age)

# Get the bird at the index of the maximum age
old_bird = bird[max_age_index]


print(max_age_index)
print(old_bird)
    

7
parrot


In [27]:
import numpy as np
def specific_elements(mat1,mat2,r1,r2,c1,c2):
    '''mat1,mat2 are the two 2d numpy array.
       r1,r2 are the start and end of rows indices
       c1,c2 are the start and end of columns indices
       Output = Return a numpy array according to indices'''
    
    # STEP1 CHECK whether matrix multiplication is possible
    
    
    ## STEP 2 Perform matrix multiplication
    
    matmul_array = np.matmul(mat1,mat2)

    
    ## STEP 3 slice the array based on range value
    
    result = matmul_array[[r1]:[r2],[c1][c2]]
    
    return result

mat1 = [[6, 6 ,4, 7 ,9],  
 [0, 2 ,2 ,9, 3]  ,
 [6, 0 ,2 ,5, 2] , 
 [2, 4 ,3 ,5, 5]]  
mat2 = [[8, 6 ,6, 8, 3]  ,
 [2, 7, 0, 3, 1]  ,
 [3, 2, 1, 5, 2]  ,
 [7, 0, 7, 6, 8]  ,
 [1 ,5 ,6 ,4 ,5]]  
r1 = 1 
r2 = 3  
c1 = 2 
c2 = 4

print(specific_elements(mat1,mat2,r1,r2,c1,c2))

IndexError: list index out of range

In [3]:
import numpy as np

def specific_elements(mat1, mat2, r1, r2, c1, c2):
    '''mat1, mat2 are the two 2d numpy arrays.
       r1, r2 are the start and end of rows indices
       c1, c2 are the start and end of columns indices
       Output = Return a numpy array according to indices'''

    # STEP 1: Check whether matrix multiplication is possible
    if mat1.shape[1] != mat2.shape[0]:
        raise ValueError("Matrix multiplication is not possible. Columns of mat1 must equal rows of mat2.")
    
    # STEP 2: Perform matrix multiplication
    matmul_array = np.matmul(mat1, mat2)

    # STEP 3: Slice the array based on range values
    result = matmul_array[r1:r2, c1:c2]
    
    return result

# Define matrices as numpy arrays
mat1 = np.array([[6, 6 ,4, 7 ,9],  
                 [0, 2 ,2 ,9, 3],
                 [6, 0 ,2 ,5, 2], 
                 [2, 4 ,3 ,5, 5]])  

mat2 = np.array([[8, 6 ,6, 8, 3],  
                 [2, 7, 0, 3, 1],
                 [3, 2, 1, 5, 2],
                 [7, 0, 7, 6, 8],
                 [1 ,5 ,6 ,4 ,5]])

r1 = 1 
r2 = 3  
c1 = 2 
c2 = 4

print(specific_elements(mat1, mat2, r1, r2, c1, c2))
print(mat1.shape[0])


[[83 82]
 [85 96]]
4


In [29]:
import numpy as np
def add_padding(mat):
    '''mat-> NumPy array
       output-> NumPy array is expected to be returned'''

    # YOUR CODE GOES HERE
    # Read input
    n, m = map(int, input().split())  # First line input for n and m
    arr = np.array([list(map(int, input().split())) for _ in range(n)])  # Next n lines for array elements

    # Create a new array with padding
    res = np.zeros((n+2, m+2), dtype=int)  # Create a (n+2) x (m+2) array of zeros

    # Fill the inner part with the original array's values
    res[1:n+1, 1:m+1] = arr
      
    return res

In [ ]:
data = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90],
                 [100, 110, 120]])

num_splits = 2
arr1 = np.vsplit(data, num_splits).tolist()

#print(np.vsplit(data, num_splits))

print(arr1.shape)



AttributeError: 'list' object has no attribute 'tolist'

In [10]:
import numpy as np

def custom_split(data, num_splits):
    # Step 1: Split the data array vertically into num_splits parts
    split_data = np.vsplit(data, num_splits)
    print(split_data)
    # Step 2: Reorder the split arrays
    # Move the last subarray to the front and the others follow
    ordered_data = np.vstack((split_data[-1], split_data[0], *split_data[1:-1]))
    
    return ordered_data

# Sample input
data = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90],
                 [100, 110, 120]])

num_splits = 2

# Get the custom split and ordered result
result = custom_split(data, num_splits)

# Output the result
print(result)


[array([[10, 20, 30],
       [40, 50, 60]]), array([[ 70,  80,  90],
       [100, 110, 120]])]
[[ 70  80  90]
 [100 110 120]
 [ 10  20  30]
 [ 40  50  60]]
